name: espitaliaa_doctors
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_screenutil: ^5.2.0
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  liquid_pull_to_refresh: ^3.0.1
  cached_network_image: ^3.2.0
  flutter_styled_toast: ^2.0.0
  flutter_spinkit: ^5.1.0
  rect_getter: 1.1.0
  intl: 0.17.0
  chips_choice: ^1.2.0
  multiselect_formfield: 0.1.7
  dotted_border: ^2.0.0
  time_range: ^1.0.2
  curved_navigation_bar: ^1.0.3
  get: ^4.6.1
  image_picker: ^0.8.0+3
  dio: ^4.0.0
  flutter_tags: ^0.4.9+1
  awesome_dialog: ^2.1.1
  firebase_messaging: ^11.4.1
  firebase_core : ^1.2.1
  flutter_local_notifications: ^9.3.2
  infinite_scroll_pagination: ^3.1.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.0.3
  place_picker: ^0.9.19
  permission_handler: ^9.2.0
  geolocator: ^8.2.1
  firebase_analytics: ^9.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/langs/

  # example:
  fonts:
    - family: appFont
      fonts:
        - asset: assets/fonts/app_font.ttf
